module practice_state_machine (
    input clk, // state machine needs to know when it is allowed to change state, so the first input we'll give it is our familiar clock
    input reset, // a way to put the state machine back into a known starting state
    // Go back to the starting state: WAITING.

    input start, // a signal that tells the state machine to switch from WAITING to ACTIVE. This signal will be generated by the user pressing a button on the FPGA board
    output active // not a state but an output to hardward that tells the user that the state machine is in the ACTIVE state. This output will be connected to an LED on the FPGA board
);
 reg state; // a register to hold the current state of the state machine. lets the state machine remember what stage it's currently in.
    // 1 bit state register is enough because we only have 2 states, therefore 4 bits can hold 16 states

localparam WAITING = 1'b0; // a local parameter is a constant that can be used in the module. It is like a variable that cannot be changed. It is used to make the code more readable. The state machine will be in the WAITING state when the state register is 0.
localparam ACTIVE  = 1'b1; // ACTIVE  is our name for 1
always @(posedge clk) begin // every time the clock goes from 0 to 1, do the following
    if (reset) begin
        state <= WAITING; // assign state a 1 bit binary value of 0, which is our name for the WAITING state
    end
    else begin
        if (state == WAITING) begin
            if (start) begin // if the state machine is in the WAITING state and the start signal is 1, then switch to the ACTIVE state
                state <= ACTIVE; // assign state a 1 bit binary value of 1, which is our name for the ACTIVE state
            end
        end
        else if (state == ACTIVE) begin // if the state machine is in the ACTIVE state
            if (!start) begin // and the start signal is 0, then switch to the WAITING state
                state <= WAITING; // assign state a 1 bit binary value of 0, which is our name for the WAITING state
            end

        end
    end
end

assign active = (state == ACTIVE); // Make active equal to 1 whenever our current state is ACTIVE.


endmodule


//clk    → WHEN do we check?
//start  → SHOULD we change state?
//state  → WHAT stage are we currently in?